apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - secretproviderclass.yaml
  - datasources.yaml
  - dashboards-provider.yaml
  - dashboards.yaml
  - deployment.yaml
  - ingress.yaml
